### ISSUE TITLE
Changer la classe 

### ISSUE THREAD

**Issue by ktzanev** [labopp/guideb2rm-sphinx#1]
Pour cette petite documentation il faut probablement passer en `article` et remplacer les chapitres par des section.

**Comment by ktzanev** [comment]
@burnol-math tu sais comment faire ça j'imagine ?

**Comment by ghost** [comment]
fixé par b46ca7c. Je n'avais pas vu que ta question correspondait au ticket #1, sinon j'aurais commencé l'intitulé du message de commit par "Fix #1: patati patata"

**Comment by ktzanev** [comment]
:+1: Génial. Que je suis content d'avoir un expert dans l'équipe !
