### ISSUE TITLE
Créer une couverture

### ISSUE THREAD

**Issue by ktzanev** [labopp/guideb2rm-sphinx#2]
Et maintenant que on utilise howto (b46ca7c112754c80c78f6089e26935b78b0a34ca) comment fait-on pour mettre une couverture ?
Des idées @burnol-math ? 
Le labopp/livretaccueil-sphinx#2 c'etait un peu trop facile ;)

Je pense qu'on peut imaginer la conception de la couverture à part et puis la rajouter comme image PDF sur une page entière juste au début.

**Comment by ktzanev** [comment]
:+1: :clap: Danke schön !

**Comment by ghost** [comment]
@ktzanev faut tout de même que j'avoue que le code ne fonctionne bien que si la table des matières a la place sur la première page; sinon elle continue sur la deuxième et le "footer" ne sera que sur la deuxième page. Il y a  de la marge pour quelques sections supplémentaires encore ... si j'ai le temps je réfléchirai à une solution un peu plus robuste :sweat_smile:

**Comment by ktzanev** [comment]
@burnol-math Pour être honette j'aurait préféré une vrai page de couverture (où on est libre de mettre ce qu'on veut) suivi du document tel quel.

**Comment by ghost** [comment]
donc le titre la table des matières etc... débutent en page 2 ?

**Comment by ghost** [comment]
bon en tout cas j'ai la méthode qui gèrera une table des matières plus longue sur deux pages. Juste un ou deux détails à régler. Je ferai ça dans une heure à peu près

**Comment by ktzanev** [comment]
Oui table et tout le tralala sur la page ... 3 si on veut une vrait couverture. L'idée est d'avoir le titre ecrit deux fois : une fois sur la couverture et une fois sur la première page avec la table des matières. Et le logo et le footer sont à mettre du coup seulement sur la couvrture.

En résumé : la doc reste sous la forme standard de "howto" et on rajoute deux pages avant (la deuxième, le verso de la couverture, étant probalemen vide).

Et l'idée est d'avoir ça pour toutes les docs : la même couverture "custom"  définie dans la config et la vraie doc, que ce soit en "howto" ou en "manual", débute en page 3 (deuxième feuille recto).

**Comment by ktzanev** [comment]
Il aurait été bien si dans les options latex de sphinx il y avait des hooks : `at_begin_header`, `at_end_header`, `at_begin_document`, `at_end_document`.

Dans ce cas même un amateur comme moi aurait pu mettre dans `at_begin_document` le rajout des deux pages.

**Comment by ktzanev** [comment]
Je realise que l'option `maketitle` est ce que je veux, c.-à-d. équivalente dans un sens à `at_begin_document`. 

Il suffit de mettre la création des deux pages dans le paramètre `maketitle` juste avant d'evoquer `\maketitle`.

**Comment by ktzanev** [comment]
Probablement aussi : 
- `passoptionstopackages`est l'équivalent de `at_begin_header`
- `preamble` est l'équivalent de `at_end_header`

il manque juste `at_end_document` ?

**Comment by ghost** [comment]
> Il aurait été bien si dans les options latex de sphinx il y avait des hooks : at_begin_header, at_end_header, at_begin_document, at_end_document.

C'est délicat en LaTeX le `at_end_document`. Il faut un package spécial qui hacke le code latex. Il y a beaucoup de complications à cause des floats. Pour les deux autres tu as découvert des clés qui font à peu près ça.

**Comment by ghost** [comment]
Bon si tu veux juste rajouter deux pages en début la clé `'maketitle'` est le mieux. On n'en avait pas parlé ailleurs ? bon bref peu importe. Je laisse en tout cas tomber mon code qui pouvait mettre les footer entremêlés avec la table des matières, même sur plusieurs pages.

Du coup le logo  n'apparaîtra que sur la page de couverture ?

Je n'ai plus beaucoup de temps aujourd'hui pour labopp.
