### ISSUE TITLE
Warnings de hyperref "duplicate ignored" à cause des pages 1 et 2 de la couverture

### ISSUE THREAD

**Issue by ghost** [labopp/guideb2rm-sphinx#4]
j'ai repoussé mon départ en vacances pour pouvoir poster le fix

(le problème est que la numérotation des pages recommence  à 1 après la couverture, ce qui perturbe hyperref -- même si les 1 et 2 de la couverture ne sont pas imprimés car Sphinx commence en `\pagestyle{empty}` en interne cela crée des identifiants identiques pour hyperref avec les pages 1 et 2 du document après la couverture)

**Comment by ktzanev** [comment]
No way ! Tu peux faire ça en septembre, non ?

**Comment by ghost** [comment]
et le pire c'est que je n'ai même pas regardé le match hier soir qui semble-t-il était pas mal.

**Comment by ktzanev** [comment]
C'est bien que tu me prévient car je suis en train de modifier le `conf.py`. Je trouve que `sphinx-quickstart` ne fait pas bien son travail : si tu veux changer le titre d'un document il faut la changer à 10 endroits dans la config ! Les informations principales doivent être au début du fichier et sans répétitions (dans la mésure du possible).

**Comment by ghost** [comment]
oui tu as raison, en général je recopie un ancien répertoire je supprime le `_build` et je fais un search/replace dans `conf.py`, ça reste plus rapide que `sphinx-quickstart`.

**Comment by ktzanev** [comment]
Si tu fais search/replace c'est que tes données "standards" ne sont pas en haut de la config. Je pense que les données qui sont à changer entre différents projets, tels `author`, `title`, ... doivent être en haut. Et après les réutiliser dans des divers endroits de la config.

**Comment by ghost** [comment]
je suis d'accord. Je fais trois trucs en même temps actuellement, pardon si je réponds pas ! ;-)

**Comment by ktzanev** [comment]
No problemo. Ton voisin ne te défonce plus les oreil ?
